#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.douyu.aoligouzi
  mapperLocations: classpath:mapper/*.xml


---

#开发配置
spring:
  profiles: dev


  dubbo:
    application:
      name: provider
    registry:
      address: zookeeper://127.0.0.1:20181
    protocol:
      name: dubbo
      prot: 20880


  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: wang123
    driver-class-name: com.mysql.jdbc.Driver

  # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
